services:
  - type: web
    name: engage-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn engage_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CARGO_HOME
        value: /tmp/.cargo

