services:
  - type: web
    name: engage-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn engage_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
