services:
  - type: web
    name: engage-backend
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn your_project.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CARGO_HOME
        value: /tmp/.cargo
