# Generated by Django 5.2.3 on 2025-06-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "campaign_id",
                    models.CharField(
                        blank=True, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("cust_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cust_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Checker", "Pending Checker"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Processed", "Processed"),
                        ],
                        default="Pending Checker",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("checker", models.CharField(blank=True, max_length=100, null=True)),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "template_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
