# Generated by Django 3.1.12 on 2025-07-14 19:05

from django.db import migrations, models
import django.db.models.deletion
import leads_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.CharField(default=leads_app.models.generate_campaign_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('status', models.CharField(choices=[('Pending Checker', 'Pending Checker'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processed', 'Processed')], default='Pending Checker', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('checker', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('template_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.template')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads_app.campaign')),
            ],
        ),
    ]
