# Generated by Django 5.2.3 on 2025-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="template_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
