# Generated by Django 5.2.3 on 2025-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_app", "0002_alter_campaign_template_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="campaign",
            field=models.CharField(max_length=10),
        ),
    ]
