# Generated by Django 5.2.3 on 2025-07-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "template_id",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[("Loan", "Loan"), ("Insurance", "Insurance")],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=30)),
                ("html_file", models.FileField(upload_to="templates_html/")),
                ("created_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
